name: exoplayer
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  uuid: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
flutter:
  plugin:
    androidPackage: danielr2001.exoplayer
    pluginClass: ExoPlayerPlugin
